Fix: Negative value when booksGoal < booksRead
Darknessflowers/Reading-Tracker pull request #1
Opened 2021-01-11 10:40 UTC by oysters76

There was a bug that I identified when the booksGoal is lesser than the booksRead. 
The text that is displayed on the screen is a negative value. Therefore I did some changes so that a message is displayed. Currently, the message says 'You have completed the goal!' when such a situation occurs. 

I have added a new function called resetFrequencyDisplayTextParagraph, which brings the paragraph back to original status, 
because the message would modify the innerHTML of the paragraph tag. 
```javascript 
const resetFrequencyDisplayTextParagraph = () => {
    frequencyDisplayText.innerHTML = "You need to finish a book every "+
      "<span id='bookFrequencyDisplay'></span> days.";
      bookFrequencyDisplay = document.querySelector('#bookFrequencyDisplay');
}
```

Before change, 
![image](https://user-images.githubusercontent.com/75514064/104170586-6337ef80-5427-11eb-8d55-e33bbc84a6dd.png)
After change
![image](https://user-images.githubusercontent.com/75514064/104170630-764abf80-5427-11eb-97e6-24cd376be419.png)

Thanks

2021-01-11 20:55 UTC, Darknessflowers requested changes
Thank you for this! Can you please add the finished books to LocalStorage as well so both values are kept?

2021-01-12 02:49 UTC, oysters76 commented
Yes sure

2021-01-12 02:57 UTC, oysters76 commented
I have added a new commit which adds the booksRead to the localstorage as well

2021-01-12 03:03 UTC, oysters76 commented on index.html
> +        <p id="frequencyDisplayText">
I added an id to this tag, so that it can be accessed in the JS code to write the message and also reset the tag

2021-01-12 03:04 UTC, oysters76 commented on scripts.js
> +const writeToLocalStorage = (goal, read) => {
This function writes to the localstorage, when the goal value and the read value are passed in. (This is only written if there is a Storage functionality in the browser)

2021-01-12 03:05 UTC, oysters76 commented on scripts.js
> +const resetFrequencyDisplayTextParagraph = () => {
This function would reset the paragraph tag to its original structure, by using the createElement and createTextNode functions of JS

2021-01-12 03:16 UTC, Darknessflowers approved these changes

2021-01-12 03:21 UTC, merged